In [469]:
import pandas as pd

#### Create a dataframe from data (dict, list, tuple,...)

##### Define the data

In [470]:
data = [["a", 1], ["b", 2], ["c", 3]]

##### Added to a dataframe

In [471]:
df = pd.DataFrame(data)

##### Then you can manipulate the dataframe or save it

- Save it to csv

In [472]:
df.to_csv("abc.csv", header=False, index=False)

- save it to xlsx

In [473]:
df.to_excel("abc.xlsx")

#### Read to a dataframe

In [474]:
data = pd.read_csv("file_1.csv")
print(data.columns)
print(data.Name)

Index(['Name', 'Age'], dtype='object')
0    Zeid
Name: Name, dtype: object

#### Dataframe manplation

- Create an empty dataframe

In [475]:
df = pd.DataFrame()
# df = pd.DataFrame()

- Adding a new column

In [476]:
df["a"] = [1, 2, 3]  # a column with values
df["b"] = ""  # a empty column
df["c"] = 0  # a column with a default value (e.g 0)
df["d"] = [4, 5, 6]  # a column with values

- Using the `insert()` method

In [477]:
df.insert(
    1,  # the index of the column
    "column_name",  # name of the column
    "value",  # the value of the column
)

- Get a column

In [478]:
result = df["a"]
result

0    1
1    2
2    3
Name: a, dtype: int64

- Get data:
    - loc: by name
    - iloc: by index

- Get a row

In [479]:
result = df.loc[1]  # row name
result

a                  2
column_name    value
b
c                  0
d                  5
Name: 1, dtype: object

In [480]:
result = df.iloc[1]  # row index
result

a                  2
column_name    value
b
c                  0
d                  5
Name: 1, dtype: object

- Get a column

In [481]:
#              row, column
result = df.loc[:, "column_name"]
result

0    value
1    value
2    value
Name: column_name, dtype: object

In [482]:
#              row, column
result = df.iloc[:, 1]
result

0    value
1    value
2    value
Name: column_name, dtype: object

- Get a value (cell)

In [483]:
#              row, column
result = df.iloc[1, 0]
result

2

In [484]:
#         row index, column
result = df.iloc[0]["a"]
result

1

In [485]:
#      index name, column name
result = df.loc[2, "a"]
result

3

- Get multiple rows and columns

In [486]:
result = df.iloc[:, [1, 3]]
result

  column_name  c
0       value  0
1       value  0
2       value  0

In [487]:
result = df.loc[:, ["a", "d"]]
result

   a  d
0  1  4
1  2  5
2  3  6

- Get rows using Conditions

In [488]:
result = df.loc[df["a"] == 1, "d"]
result

0    4
Name: d, dtype: int64

In [489]:
result = df.loc[(df["a"] == 1) & (df["d"] != 1)]
result

   a column_name b  c  d
0  1       value    0  4

- `get()` method

In [490]:
result=df.get("d",default="Null")
result

0    4
1    5
2    6
Name: d, dtype: int64

In [491]:
result=df.get("g",default="1")
result

'1'

- add a value to row

In [492]:
df.loc[df.index[1], "b"] = "13"
df

   a column_name   b  c  d
0  1       value      0  4
1  2       value  13  0  5
2  3       value      0  6

- Append a row

In [493]:
df.loc[len(df)] = [4, "value", 14, 0, 7]
df

   a column_name   b  c  d
0  1       value      0  4
1  2       value  13  0  5
2  3       value      0  6
3  4       value  14  0  7

- `isin()` method

In [494]:
df["e"] = df["a"].isin([1, 3])
df

   a column_name   b  c  d      e
0  1       value      0  4   True
1  2       value  13  0  5  False
2  3       value      0  6   True
3  4       value  14  0  7  False

- Shift a column

In [495]:
df["prev_a"] = df["a"].shift()  # shift down
df["next_a"] = df["a"].shift(-1)  # shift up
df

   a column_name   b  c  d      e  prev_a  next_a
0  1       value      0  4   True     NaN     2.0
1  2       value  13  0  5  False     1.0     3.0
2  3       value      0  6   True     2.0     4.0
3  4       value  14  0  7  False     3.0     NaN

- Compare columns

In [496]:
df["equal"] = df["a"].eq(df["d"])
df

   a column_name   b  c  d      e  prev_a  next_a  equal
0  1       value      0  4   True     NaN     2.0  False
1  2       value  13  0  5  False     1.0     3.0  False
2  3       value      0  6   True     2.0     4.0  False
3  4       value  14  0  7  False     3.0     NaN  False

- Apply a function to each row or column using `apply()`

In [497]:
df1 = df.apply(lambda x: x * 10, axis=0)  # rows
df2 = df.apply(lambda x: x * 5, axis=1)  # columns

In [498]:
df1

,a,column_name,b,c,d,e,prev_a,next_a,equal
0,10,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,,0,40,10,NaN,20.0,0
1,20,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,13131313131313131313,0,50,0,10.0,30.0,0
2,30,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,,0,60,10,20.0,40.0,0
3,40,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,140,0,70,0,30.0,NaN,0

In [499]:
df2

    a                column_name           b  c   d  e  prev_a  next_a  equal
0   5  valuevaluevaluevaluevalue              0  20  5     NaN    10.0      0
1  10  valuevaluevaluevaluevalue  1313131313  0  25  0     5.0    15.0      0
2  15  valuevaluevaluevaluevalue              0  30  5    10.0    20.0      0
3  20  valuevaluevaluevaluevalue          70  0  35  0    15.0     NaN      0

In [500]:
def squaredata(x):
    return x * x

In [501]:
df3 = df["d"].apply(squaredata)
df3

0    16
1    25
2    36
3    49
Name: d, dtype: int64

In [502]:
df["new_col"] = df.apply(lambda row: row.iloc[0] + row.iloc[3] + row.iloc[4], axis=1)
df

   a column_name   b  c  d      e  prev_a  next_a  equal  new_col
0  1       value      0  4   True     NaN     2.0  False        5
1  2       value  13  0  5  False     1.0     3.0  False        7
2  3       value      0  6   True     2.0     4.0  False        9
3  4       value  14  0  7  False     3.0     NaN  False       11

- Concatenate DataFrames

In [503]:
df4 = pd.concat([df1, df3])
df4

,a,column_name,b,c,d,e,prev_a,next_a,equal,0
0,10.0,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,,0.0,40.0,10.0,NaN,20.0,0.0,NaN
1,20.0,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,13131313131313131313,0.0,50.0,0.0,10.0,30.0,0.0,NaN
2,30.0,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,,0.0,60.0,10.0,20.0,40.0,0.0,NaN
3,40.0,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,140,0.0,70.0,0.0,30.0,NaN,0.0,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0

In [504]:
df5 = pd.concat([df1, df3], axis=1)
df5

,a,column_name,b,c,d,e,prev_a,next_a,equal,d
0,10,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,,0,40,10,NaN,20.0,0,16
1,20,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,13131313131313131313,0,50,0,10.0,30.0,0,25
2,30,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,,0,60,10,20.0,40.0,0,36
3,40,valuevaluevaluevaluevaluevaluevaluevaluevaluev...,140,0,70,0,30.0,NaN,0,49

In [505]:
countries = {
    1: {
        "Country": "New Country 1",
        "Capital": "New Capital 1",
        "Population": "123,456,789",
    },
    2: {
        "Country": "New Country 2",
        "Capital": "New Capital 2",
        "Population": "987,654,321",
    },
    3: {
        "Country": "New Country 3",
        "Capital": "New Capital 3",
        "Population": "111,222,333",
    },
}

df6 = pd.DataFrame.from_dict(countries, orient="index")
df6

         Country        Capital   Population
1  New Country 1  New Capital 1  123,456,789
2  New Country 2  New Capital 2  987,654,321
3  New Country 3  New Capital 3  111,222,333

- Save the dataframes into a single xlsx file with multiple sheets

In [506]:
with pd.ExcelWriter(f"files.xlsx", mode="w") as writer:
    df.to_excel(writer, index=False, sheet_name="df")
    df1.to_excel(writer, index=False, sheet_name="df1")
    df2.to_excel(writer, index=False, sheet_name="df2")

In [507]:
with pd.ExcelWriter(f"files.xlsx", mode="a") as writer: # append
    df3.to_excel(writer, index=False, sheet_name="df3")
    df4.to_excel(writer, index=False, sheet_name="df4")
    df5.to_excel(writer, index=False, sheet_name="df5")
    df6.to_excel(writer, index=False, sheet_name="df6")

- Sort values

In [508]:
df.sort_values(by=["a", "d"], ascending=True, axis=0)

   a column_name   b  c  d      e  prev_a  next_a  equal  new_col
0  1       value      0  4   True     NaN     2.0  False        5
1  2       value  13  0  5  False     1.0     3.0  False        7
2  3       value      0  6   True     2.0     4.0  False        9
3  4       value  14  0  7  False     3.0     NaN  False       11

In [509]:
df.sort_values(by=["a", "d"], ascending=False, axis=0)

   a column_name   b  c  d      e  prev_a  next_a  equal  new_col
3  4       value  14  0  7  False     3.0     NaN  False       11
2  3       value      0  6   True     2.0     4.0  False        9
1  2       value  13  0  5  False     1.0     3.0  False        7
0  1       value      0  4   True     NaN     2.0  False        5

- `drop()` method

In [510]:
df["a"]==1

0     True
1    False
2    False
3    False
Name: a, dtype: bool

In [511]:
df[df["a"]==1]

   a column_name b  c  d     e  prev_a  next_a  equal  new_col
0  1       value    0  4  True     NaN     2.0  False        5

In [512]:
df.loc[df["d"]==5]

   a column_name   b  c  d      e  prev_a  next_a  equal  new_col
1  2       value  13  0  5  False     1.0     3.0  False        7

In [513]:
df.drop(df.loc[df["d"]==5].index, inplace=True)
df

   a column_name   b  c  d      e  prev_a  next_a  equal  new_col
0  1       value      0  4   True     NaN     2.0  False        5
2  3       value      0  6   True     2.0     4.0  False        9
3  4       value  14  0  7  False     3.0     NaN  False       11

In [514]:
df.drop(df[df["a"]==1].index, inplace=True)
df

   a column_name   b  c  d      e  prev_a  next_a  equal  new_col
2  3       value      0  6   True     2.0     4.0  False        9
3  4       value  14  0  7  False     3.0     NaN  False       11

In [515]:
df.drop(columns=["column_name"], inplace=True)
df

   a   b  c  d      e  prev_a  next_a  equal  new_col
2  3      0  6   True     2.0     4.0  False        9
3  4  14  0  7  False     3.0     NaN  False       11

In [516]:
df

   a   b  c  d      e  prev_a  next_a  equal  new_col
2  3      0  6   True     2.0     4.0  False        9
3  4  14  0  7  False     3.0     NaN  False       11